name: Sloth Circuit Tests
on: [push, pull_request]
jobs:
  SlothTest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Sloth circuit simulator tests
      run: cd tests/sloth && ./run
